# fly.toml app configuration file generated for mission-minio on 2023-09-06T20:33:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mission-minio"
primary_region = "lax"

[http_service]
  internal_port = 9000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
source="miniodata"
destination="/data"

[[services]]
